### ISSUE TITLE
"Playing iTunes/Apple Music" depending on what's playing

### ISSUE THREAD

**Issue by MattrAus** [nint8835/iTunesRichPresence#33]
Not sure how feasible this could be, but it would be nice to change the _PLAYING A GAME iTunes_ or _PLAYING A GAME Apple Music_ depending on if you're listening to a song on Apple Music or just a local copy through iTunes.

Files are either determined as "**iCloud status** Apple Music" or "**iCloud Status** Uploaded", so I'm not sure if you could use this to determine whether they're apple music or local.

**Comment by nint8835** [comment]
The API I'm using to interact with iTunes was last updated in like 2009, so I *highly* doubt that it has support for determining whether or not you're using apple music. Additionally, since the thing that uses the app name is the same thing that interacts with iTunes, it isn't really very easy to go and swap out that text on the fly.
