### ISSUE TITLE
May or may not be working on Windows 11

### ISSUE THREAD

**Issue by Vistril** [nint8835/iTunesRichPresence#91]
Noticed no one else has made an issue pertaining usage on Windows 11. With that being said, I am unable to have it working on Windows 11.. I cannot confirm nor deny this, though, as I have no reliable way to test..

I have tried the following:

- Complete restart of OS, iTunes, Discord and iTunesRP
- Added iTunesRP as a game manually
- Made sure Discord or iTunesRP wasn't sandboxed somehow

iTunesRP is definitely "hooked" in, as iTunes is not willing to exit while it runs. I can also use the experiments tab.

Anything else I should try?

```
Windows 11 details: 
Edition	Windows 11 Pro
Version	21H2
Installed on	‎7/‎31/‎2021
OS build	22000.194
Experience	Windows Feature Experience Pack 1000.22000.194.0
```
```
Discord details: (this could contribute to the issue, maybe?)
Canary 100077 (30bec47) 
Host 1.0.616 
Windows 10 64-Bit (10.0.22000)
```

**Comment by camcielinski** [comment]
I am also having this problem! It seems to be a Windows 11 issue.

**Comment by ChrisChrome** [comment]
Same here

**Comment by Monochromish** [comment]
I am running Windows 11 Home Edition, and I am running Discord Canary as well but the rich presence seems to work for me.
What you could try to fix your rich presence is:

- [x] Check whether you have Activity Status turned on from Discord Settings > Activity Status

![HZyre3m9fq](https://user-images.githubusercontent.com/79590499/146511373-3e026e8f-46ce-4fb2-96d9-3a96adfe4682.gif)

- [x] Check whether you have offline presence turned on, since offline presence completely removes all rich presence

![0WLReNt0O4](https://user-images.githubusercontent.com/79590499/146511480-26f38a66-911a-4430-8381-b3b6d582a51e.gif)

- [x] Remove your custom status if you have one

![xvgxjjZ12d](https://user-images.githubusercontent.com/79590499/146511620-e90bf844-4c4c-4304-a39c-af60150e39a7.gif)

If you do all of the above and if the status still does not seem to work for you, then I would recommend using Discord PTB or the stable version rather than the canary version.

**Comment by camcielinski** [comment]
Hello,
It appears that the app has started working as of a few days ago. My
apologies for not replying with this update sooner.
I am guessing that Microsoft pushed a Windows 11 update that
fixed…something. But it started working recently.
Thank you!

**Comment by Vistril** [comment]
Working on Windows 11 now all of a sudden. Forgot I made this issue. 
Will keep open though as other people seem to have the issue.

**Comment by nint8835** [comment]
Closing due to iTunesRichPresence no longer being maintained.
